name: Lint & Typecheck
on:
  push:

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      # PACKAGE_MANAGER_SETUP_START
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      # PACKAGE_MANAGER_SETUP_END

      - name: Install dependencies
        run: PACKAGE_MANAGER install

      - name: Run lint
        run: PACKAGE_MANAGER lint

      - name: Run typecheck
        run: PACKAGE_MANAGER typecheck
